title: OS2compliance documentation
description: This repository contains documentation for OS2compliance
theme: just-the-docs

url: https://os2compliance.github.io/OS2compliance-docs/

logo: /assets/OS2compliance_logo.svg

aux_links:
  github.com/os2compliance: https://github.com/OS2compliance/OS2compliance
  os2.eu/os2compliance: https://www.os2.eu/os2compliance
